// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vlog.Models;

namespace Vlog.Migrations
{
    [DbContext(typeof(VlogDBContext))]
    partial class VlogDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Vlog.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EstablishedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompanyItems");
                });

            modelBuilder.Entity("Vlog.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContactEnum")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactItems");
                });

            modelBuilder.Entity("Vlog.Models.Types.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegencyId")
                        .HasColumnType("int");

                    b.Property<string>("Rural")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specific")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RegencyId");

                    b.ToTable("AddressItems");
                });

            modelBuilder.Entity("Vlog.Models.Types.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CountryItems");
                });

            modelBuilder.Entity("Vlog.Models.Types.LogisticFareIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogisticFareIdentityItems");
                });

            modelBuilder.Entity("Vlog.Models.Types.LogisticOtherService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogisticOtherServiceItems");
                });

            modelBuilder.Entity("Vlog.Models.Types.LogisticOtherServiceFare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LogisticOtherServiceId")
                        .HasColumnType("int");

                    b.Property<int>("LogisticUnit")
                        .HasColumnType("int");

                    b.Property<decimal>("Nominal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LogisticOtherServiceId");

                    b.ToTable("LogisticOtherServiceFareItems");
                });

            modelBuilder.Entity("Vlog.Models.Types.LogisticPacket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressFromId")
                        .HasColumnType("int");

                    b.Property<int?>("AddressToId")
                        .HasColumnType("int");

                    b.Property<string>("AirWayBill")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CurrentNominal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LogisticServiceId")
                        .HasColumnType("int");

                    b.Property<string>("NameFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressFromId");

                    b.HasIndex("AddressToId");

                    b.HasIndex("LogisticServiceId");

                    b.ToTable("LogisticPacketItems");
                });

            modelBuilder.Entity("Vlog.Models.Types.LogisticService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ROMargin")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("LogisticServiceItems");
                });

            modelBuilder.Entity("Vlog.Models.Types.LogisticServiceFare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LogisticServiceId")
                        .HasColumnType("int");

                    b.Property<int>("LogisticUnit")
                        .HasColumnType("int");

                    b.Property<int>("MaximumEstimateDay")
                        .HasColumnType("int");

                    b.Property<int>("MinimumEstimateDay")
                        .HasColumnType("int");

                    b.Property<decimal>("Nominal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RegencyFromId")
                        .HasColumnType("int");

                    b.Property<int?>("RegencyToId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LogisticServiceId");

                    b.HasIndex("RegencyFromId");

                    b.HasIndex("RegencyToId");

                    b.ToTable("LogisticServiceFarelItems");
                });

            modelBuilder.Entity("Vlog.Models.Types.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("ProvinceItems");
                });

            modelBuilder.Entity("Vlog.Models.Types.RajaOngkirCity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ROCityId")
                        .HasColumnType("int");

                    b.Property<int?>("RegencyId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RegencyId");

                    b.ToTable("RajaOngkirCityItems");
                });

            modelBuilder.Entity("Vlog.Models.Types.RajaOngkirProvince", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<int>("ROProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("RajaOngkirProvinceItems");
                });

            modelBuilder.Entity("Vlog.Models.Types.Regency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("RegencyItems");
                });

            modelBuilder.Entity("Vlog.Models.Types.Rural", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegencyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegencyId");

                    b.ToTable("RuralItems");
                });

            modelBuilder.Entity("Vlog.Models.Types.UserRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRoleEnum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("UserRoleItems");
                });

            modelBuilder.Entity("Vlog.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserItems");
                });

            modelBuilder.Entity("Vlog.Models.Types.Address", b =>
                {
                    b.HasOne("Vlog.Models.Types.Regency", "Regency")
                        .WithMany()
                        .HasForeignKey("RegencyId");
                });

            modelBuilder.Entity("Vlog.Models.Types.LogisticOtherServiceFare", b =>
                {
                    b.HasOne("Vlog.Models.Types.LogisticOtherService", "LogisticOtherService")
                        .WithMany()
                        .HasForeignKey("LogisticOtherServiceId");
                });

            modelBuilder.Entity("Vlog.Models.Types.LogisticPacket", b =>
                {
                    b.HasOne("Vlog.Models.Types.Address", "AddressFrom")
                        .WithMany()
                        .HasForeignKey("AddressFromId");

                    b.HasOne("Vlog.Models.Types.Address", "AddressTo")
                        .WithMany()
                        .HasForeignKey("AddressToId");

                    b.HasOne("Vlog.Models.Types.LogisticService", "LogisticService")
                        .WithMany()
                        .HasForeignKey("LogisticServiceId");
                });

            modelBuilder.Entity("Vlog.Models.Types.LogisticServiceFare", b =>
                {
                    b.HasOne("Vlog.Models.Types.LogisticService", "LogisticService")
                        .WithMany()
                        .HasForeignKey("LogisticServiceId");

                    b.HasOne("Vlog.Models.Types.Regency", "RegencyFrom")
                        .WithMany()
                        .HasForeignKey("RegencyFromId");

                    b.HasOne("Vlog.Models.Types.Regency", "RegencyTo")
                        .WithMany()
                        .HasForeignKey("RegencyToId");
                });

            modelBuilder.Entity("Vlog.Models.Types.Province", b =>
                {
                    b.HasOne("Vlog.Models.Types.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");
                });

            modelBuilder.Entity("Vlog.Models.Types.RajaOngkirCity", b =>
                {
                    b.HasOne("Vlog.Models.Types.Regency", "Regency")
                        .WithMany()
                        .HasForeignKey("RegencyId");
                });

            modelBuilder.Entity("Vlog.Models.Types.RajaOngkirProvince", b =>
                {
                    b.HasOne("Vlog.Models.Types.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId");
                });

            modelBuilder.Entity("Vlog.Models.Types.Regency", b =>
                {
                    b.HasOne("Vlog.Models.Types.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId");
                });

            modelBuilder.Entity("Vlog.Models.Types.Rural", b =>
                {
                    b.HasOne("Vlog.Models.Types.Regency", "Regency")
                        .WithMany()
                        .HasForeignKey("RegencyId");
                });

            modelBuilder.Entity("Vlog.Models.Types.UserRole", b =>
                {
                    b.HasOne("Vlog.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");
                });
#pragma warning restore 612, 618
        }
    }
}
